// <auto-generated />
using System;
using LCWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250611021558_AddedAuthModels")]
    partial class AddedAuthModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCWeb.Shared.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Auth.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.DraftLC.DraftLCSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LCStatus")
                        .HasColumnType("int");

                    b.Property<string>("S10BankCharges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S11TermsAndCond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1Confirmation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("S1Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("S1Enclosure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1LCType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1PONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("S2DateOfExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("S2IssuingBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2PlaceOfExpiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3AdvisingBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3CreditAvailBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3CreditAvailWith")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3DifferredRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3DraftAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3SwiftCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S4BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("S4Currency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("S4Figures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("S4ForexRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("S4ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("S4LCAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("S5TTReimbursement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6MannerOfShipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6ShipmentTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("S7LCAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("S7LatestShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("S7Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ShipmentFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ShipmentTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8PartialShipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8Transhipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S9ReqDocuments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DraftLCSections");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.LC.LetterOfCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("datetime2");

                    b.Property<int>("DraftLCSectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LCStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("LatestShipDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningBank")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DraftLCSectionId");

                    b.ToTable("LetterOfCredits");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Maintenance.AmendmentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningBank1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningBank2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AmendmentReports");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Maintenance.MonitoringReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenedTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpeningBank1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningBank2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonitoringReports");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Maintenance.VendorMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorMaintenances");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Auth.UserDetails", b =>
                {
                    b.HasOne("LCWeb.Shared.Models.Auth.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("LCWeb.Shared.Models.Auth.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.LC.LetterOfCredit", b =>
                {
                    b.HasOne("LCWeb.Shared.Models.DraftLC.DraftLCSection", "DraftLCSection")
                        .WithMany("LetterOfCredits")
                        .HasForeignKey("DraftLCSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftLCSection");
                });

            modelBuilder.Entity("LCWeb.Shared.Models.Auth.User", b =>
                {
                    b.Navigation("UserDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("LCWeb.Shared.Models.DraftLC.DraftLCSection", b =>
                {
                    b.Navigation("LetterOfCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
