// <auto-generated />
using System;
using LCWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250530030917_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LCWeb.Shared.Models.DraftLC.DraftLCSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("S10BankCharges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S11TermsAndCond")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1Confirmation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1Enclosure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1LCType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1PONo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("S2DateOfExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("S2IssuingBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2PlaceOfExpiry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3AdvisingBank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3CreditAvailBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3CreditAvailWith")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3DifferredRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3DraftAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3SwiftCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S4BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S4ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("S4LCAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("S5TTReimbursement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6MannerOfShipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6ShipmentTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("S7LCAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("S7LatestShipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("S7Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ShipmentFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7ShipmentTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8PartialShipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8Transhipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S9ReqDocuments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DraftLCSections");
                });
#pragma warning restore 612, 618
        }
    }
}
